language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - python setup.py install
  - sudo rm -rf ccy
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script: python -m runtests

# Only test master and dev
branches:
  only:
    - master
    - dev
