language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - python setup.py install
  - pip install -r requirements-dev.txt

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then flake8; fi
  - rm -rf ccy
  - rm -rf ccy.egg-info
  - ls -la
  - coverage run runtests.py

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then coveralls; fi

notifications:
  email: false

# Only test master and dev
branches:
  only:
    - master
