language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - python setup.py install
  - pip install -r requirements_dev.txt --use-mirrors
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; pep8 ccy tests; fi
  - sudo rm -rf ccy
  - coverage run runtests.py

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then coveralls; fi

notifications:
  email: false

# Only test master and dev
branches:
  only:
    - master
    - dev
