language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - python setup.py install
  - pip install -r requirements_dev.txt

script:
  - if [[ $TRAVIS_PYTHON_VERSION >= '3.4' ]]; then pep8; fi
  - sudo rm -rf ccy
  - sudo rm -rf ccy.egg-info
  - coverage run runtests.py

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION >= '3.4' ]]; then coveralls; fi

notifications:
  email: false

# Only test master and dev
branches:
  only:
    - master
