language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - python setup.py install
  - pip install -r requirements_dev.txt --use-mirrors
  - sudo rm -rf ccy
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

script:
  coverage run runtests.py

after_success:
  - coveralls

# Only test master and dev
branches:
  only:
    - master
    - dev
