language: python

python:
  - "2.7"
  - "3.4.4"
  - "3.5.2"
  - "3.6.1"
  - "3.7-dev"
  - "pypy"

install:
  - pip install -r requirements-dev.txt

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6.1' ]]; then flake8; fi
  - coverage run setup.py test

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6.1' ]]; then coveralls; fi

notifications:
  email: false

